const std = @import("std");
const cli = @import("cli");
const registry = @import("registry.zig");
const tool_command = @import("tool_command.zig");
const init_cli = @import("init.zig");
const serve_cli = @import("serve.zig");
const upgrade_cli = @import("upgrade.zig");
const version = @import("../version.zig").version;

/// Build the top-level cli.App for zpm.
///
/// init + serve + upgrade + every entry in `registry.tool_defs_for_app`.
/// Each tool command is generated by `tool_command.ToolCommand(def)`.
pub fn buildApp(runner: *cli.AppRunner) !cli.App {
    return cli.App{
        .version = version,
        .command = cli.Command{
            .name = "zpm",
            .description = .{ .one_line = "Prolog inference engine for the Model Context Protocol" },
            .target = .{ .subcommands = try assembleCommands(runner) },
        },
    };
}

fn versionAction() anyerror!void {
    const stdout: std.fs.File = .{ .handle = std.posix.STDOUT_FILENO };
    stdout.writeAll("zpm " ++ version ++ "\n") catch {};
}

fn assembleCommands(runner: *cli.AppRunner) ![]cli.Command {
    const defs = registry.tool_defs_for_app;
    var tmp: [defs.len + 4]cli.Command = undefined;

    tmp[0] = cli.Command{
        .name = "init",
        .description = .{ .one_line = "Initialize a .zpm/ project directory" },
        .target = .{ .action = .{ .exec = init_cli.initAction } },
    };
    tmp[1] = cli.Command{
        .name = "serve",
        .description = .{ .one_line = "Start the MCP server on stdio" },
        .target = .{ .action = .{ .exec = serve_cli.serveAction } },
    };
    tmp[2] = try upgrade_cli.buildCommand(runner);
    tmp[3] = cli.Command{
        .name = "version",
        .description = .{ .one_line = "Print zpm version and exit" },
        .target = .{ .action = .{ .exec = versionAction } },
    };

    // Static dispatch on each comptime-known def — required because
    // ToolCommand(def) is a distinct type per def.
    inline for (defs, 0..) |def, i| {
        tmp[4 + i] = try tool_command.ToolCommand(def).build(runner);
    }
    return runner.allocCommands(tmp[0..]);
}

test "buildApp returns app with 26 subcommands" {
    var runner = try cli.AppRunner.init(std.testing.allocator);
    defer runner.deinit();
    const app = try buildApp(&runner);
    try std.testing.expect(app.command.target == .subcommands);
    try std.testing.expectEqual(@as(usize, 26), app.command.target.subcommands.len);
}

test "buildApp first four subcommands are init, serve, upgrade, version" {
    var runner = try cli.AppRunner.init(std.testing.allocator);
    defer runner.deinit();
    const app = try buildApp(&runner);
    const subs = app.command.target.subcommands;
    try std.testing.expectEqualStrings("init", subs[0].name);
    try std.testing.expectEqualStrings("serve", subs[1].name);
    try std.testing.expectEqualStrings("upgrade", subs[2].name);
    try std.testing.expectEqualStrings("version", subs[3].name);
}

test "buildApp tool subcommands match registry kebab names" {
    var runner = try cli.AppRunner.init(std.testing.allocator);
    defer runner.deinit();
    const app = try buildApp(&runner);
    const subs = app.command.target.subcommands;
    const defs = registry.all();
    for (defs, 0..) |def, i| {
        try std.testing.expectEqualStrings(def.cli_name, subs[4 + i].name);
    }
}

test "buildApp every tool subcommand has --format option" {
    var runner = try cli.AppRunner.init(std.testing.allocator);
    defer runner.deinit();
    const app = try buildApp(&runner);
    const subs = app.command.target.subcommands;
    var idx: usize = 4;
    while (idx < subs.len) : (idx += 1) {
        const opts = subs[idx].options orelse return error.MissingOptions;
        var found = false;
        for (opts) |o| if (std.mem.eql(u8, o.long_name, "format")) {
            found = true;
            break;
        };
        try std.testing.expect(found);
    }
}
